/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_model_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[36] = {13, 12, 0, 1, 2, 3, 7, 11, 15, 16, 17, 18, 19, 20, 21, 0, 1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s4[3] = {12, 0, 0};

/* payload_model_cost_y_e_fun_jac_ut_xt:(i0[13],i1[],i2[],i3[],i4[])->(o0[12],o1[13x12,21nz],o2[12x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=2.;
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a3=(a1*a2);
  a4=arg[0]? arg[0][5] : 0;
  a5=arg[0]? arg[0][6] : 0;
  a6=(a4*a5);
  a3=(a3+a6);
  a3=(a0*a3);
  a6=1.;
  a7=casadi_sq(a2);
  a8=casadi_sq(a4);
  a7=(a7+a8);
  a7=(a0*a7);
  a7=(a6-a7);
  a8=atan2(a3,a7);
  if (res[0]!=0) res[0][3]=a8;
  a8=(a1*a4);
  a9=(a5*a2);
  a8=(a8-a9);
  a8=(a0*a8);
  a9=casadi_fabs(a8);
  a9=(a6<=a9);
  a10=3.1415926535897931e+00;
  a11=casadi_sign(a8);
  a10=(a10*a11);
  a10=(a10/a0);
  a10=(a9?a10:0);
  a9=(!a9);
  a11=asin(a8);
  a11=(a9?a11:0);
  a10=(a10+a11);
  if (res[0]!=0) res[0][4]=a10;
  a10=(a1*a5);
  a11=(a2*a4);
  a10=(a10+a11);
  a10=(a0*a10);
  a11=casadi_sq(a4);
  a12=casadi_sq(a5);
  a11=(a11+a12);
  a11=(a0*a11);
  a11=(a6-a11);
  a12=atan2(a10,a11);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][7]=a12;
  a12=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][8]=a12;
  a12=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a12;
  a12=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a12;
  a12=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a12;
  if (res[1]!=0) res[1][0]=a6;
  if (res[1]!=0) res[1][1]=a6;
  if (res[1]!=0) res[1][2]=a6;
  a12=casadi_sq(a3);
  a13=casadi_sq(a7);
  a12=(a12+a13);
  a7=(a7/a12);
  a13=(a0*a2);
  a13=(a7*a13);
  if (res[1]!=0) res[1][3]=a13;
  a13=(a0*a1);
  a13=(a7*a13);
  a3=(a3/a12);
  a12=(a2+a2);
  a12=(a0*a12);
  a12=(a3*a12);
  a13=(a13+a12);
  if (res[1]!=0) res[1][4]=a13;
  a13=(a0*a5);
  a13=(a7*a13);
  a12=(a4+a4);
  a12=(a0*a12);
  a3=(a3*a12);
  a13=(a13+a3);
  if (res[1]!=0) res[1][5]=a13;
  a13=(a0*a4);
  a7=(a7*a13);
  if (res[1]!=0) res[1][6]=a7;
  a7=(a0*a4);
  a8=casadi_sq(a8);
  a8=(a6-a8);
  a8=sqrt(a8);
  a7=(a7/a8);
  a7=(a9?a7:0);
  if (res[1]!=0) res[1][7]=a7;
  a7=(a0*a5);
  a7=(a7/a8);
  a7=(-a7);
  a7=(a9?a7:0);
  if (res[1]!=0) res[1][8]=a7;
  a7=(a0*a1);
  a7=(a7/a8);
  a7=(a9?a7:0);
  if (res[1]!=0) res[1][9]=a7;
  a7=(a0*a2);
  a7=(a7/a8);
  a7=(-a7);
  a9=(a9?a7:0);
  if (res[1]!=0) res[1][10]=a9;
  a9=casadi_sq(a10);
  a7=casadi_sq(a11);
  a9=(a9+a7);
  a11=(a11/a9);
  a7=(a0*a5);
  a7=(a11*a7);
  if (res[1]!=0) res[1][11]=a7;
  a7=(a0*a4);
  a7=(a11*a7);
  if (res[1]!=0) res[1][12]=a7;
  a2=(a0*a2);
  a2=(a11*a2);
  a10=(a10/a9);
  a4=(a4+a4);
  a4=(a0*a4);
  a4=(a10*a4);
  a2=(a2+a4);
  if (res[1]!=0) res[1][13]=a2;
  a1=(a0*a1);
  a11=(a11*a1);
  a5=(a5+a5);
  a0=(a0*a5);
  a10=(a10*a0);
  a11=(a11+a10);
  if (res[1]!=0) res[1][14]=a11;
  if (res[1]!=0) res[1][15]=a6;
  if (res[1]!=0) res[1][16]=a6;
  if (res[1]!=0) res[1][17]=a6;
  if (res[1]!=0) res[1][18]=a6;
  if (res[1]!=0) res[1][19]=a6;
  if (res[1]!=0) res[1][20]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_model_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_model_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_model_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int payload_model_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real payload_model_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
