/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) payload_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};

/* payload_model_constr_h_fun:(i0[13],i1[9],i2[],i3[22])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=-1.5400000000000000e-01;
  a1=5.0000000000000000e-01;
  a2=3.3333333333333337e-01;
  a3=1.;
  a4=2.;
  a5=arg[0]? arg[0][8] : 0;
  a6=casadi_sq(a5);
  a6=(a4*a6);
  a7=(a3-a6);
  a8=arg[0]? arg[0][9] : 0;
  a9=casadi_sq(a8);
  a9=(a4*a9);
  a7=(a7-a9);
  a10=arg[1]? arg[1][0] : 0;
  a7=(a7*a10);
  a11=arg[0]? arg[0][7] : 0;
  a12=(a4*a11);
  a13=(a12*a5);
  a14=(a4*a8);
  a15=arg[0]? arg[0][6] : 0;
  a14=(a14*a15);
  a16=(a13+a14);
  a17=arg[1]? arg[1][1] : 0;
  a16=(a16*a17);
  a7=(a7+a16);
  a16=(a12*a8);
  a5=(a4*a5);
  a18=(a5*a15);
  a19=(a16-a18);
  a20=arg[1]? arg[1][2] : 0;
  a19=(a19*a20);
  a7=(a7+a19);
  a2=(a2*a7);
  a19=-9.3664866266566783e-05;
  a13=(a13-a14);
  a13=(a13*a10);
  a11=casadi_sq(a11);
  a4=(a4*a11);
  a3=(a3-a4);
  a9=(a3-a9);
  a9=(a9*a17);
  a13=(a13+a9);
  a5=(a5*a8);
  a12=(a12*a15);
  a15=(a5+a12);
  a15=(a15*a20);
  a13=(a13+a15);
  a19=(a19*a13);
  a19=(a2+a19);
  a15=-6.8474457682476854e-18;
  a16=(a16+a18);
  a16=(a16*a10);
  a5=(a5-a12);
  a5=(a5*a17);
  a16=(a16+a5);
  a3=(a3-a6);
  a3=(a3*a20);
  a16=(a16+a3);
  a15=(a15*a16);
  a19=(a19+a15);
  a15=-3.7301968774698292e-17;
  a3=arg[1]? arg[1][3] : 0;
  a15=(a15*a3);
  a19=(a19+a15);
  a15=3.0618814108740516e-18;
  a20=arg[1]? arg[1][4] : 0;
  a15=(a15*a20);
  a19=(a19+a15);
  a15=9.3664866266566860e-01;
  a6=arg[1]? arg[1][5] : 0;
  a15=(a15*a6);
  a19=(a19+a15);
  a15=-2.8791878364968609e-01;
  a5=arg[1]? arg[1][6] : 0;
  a15=(a15*a5);
  a17=2.1489778834990589e-01;
  a12=arg[1]? arg[1][7] : 0;
  a17=(a17*a12);
  a15=(a15+a17);
  a17=-5.3619323785267692e-01;
  a10=arg[1]? arg[1][8] : 0;
  a17=(a17*a10);
  a15=(a15+a17);
  a19=(a19-a15);
  a15=casadi_sq(a19);
  a17=-3.1060030929663135e-18;
  a17=(a17*a7);
  a18=3.3338739234416359e-01;
  a18=(a18*a13);
  a17=(a17+a18);
  a18=-2.1286995380633428e-17;
  a18=(a18*a16);
  a17=(a17+a18);
  a18=-1.0875972739626700e-16;
  a18=(a18*a3);
  a17=(a17+a18);
  a18=2.9410312661678794e-16;
  a18=(a18*a20);
  a17=(a17+a18);
  a18=-5.4059010830254539e-01;
  a18=(a18*a6);
  a17=(a17+a18);
  a18=-4.6951496801223969e-01;
  a18=(a18*a5);
  a8=-5.5309765359110619e-01;
  a8=(a8*a12);
  a18=(a18+a8);
  a8=-2.3874758926892375e-01;
  a8=(a8*a10);
  a18=(a18+a8);
  a17=(a17-a18);
  a18=casadi_sq(a17);
  a15=(a15+a18);
  a18=-1.2167423750811156e-02;
  a18=(a18*a7);
  a8=-2.1067415730337036e-02;
  a8=(a8*a13);
  a8=(a18+a8);
  a9=3.3344148821111835e-01;
  a9=(a9*a16);
  a8=(a8+a9);
  a9=-1.8726591760299598e+00;
  a9=(a9*a3);
  a8=(a8+a9);
  a9=1.0815487778498807e+00;
  a9=(a9*a20);
  a8=(a8+a9);
  a4=9.8927468269408023e-18;
  a4=(a4*a6);
  a8=(a8+a4);
  a4=5.5511151231257827e-17;
  a4=(a4*a5);
  a11=2.7755575615628914e-17;
  a14=(a11*a12);
  a4=(a4+a14);
  a14=-1.5265566588595902e-16;
  a14=(a14*a10);
  a4=(a4+a14);
  a8=(a8-a4);
  a4=casadi_sq(a8);
  a15=(a15+a4);
  a15=sqrt(a15);
  a4=9.9999999999999995e-07;
  a15=(a15+a4);
  a19=(a19/a15);
  a19=(a1*a19);
  a19=(a0+a19);
  a14=3.0830000000000002e-01;
  a21=6.1893582144885192e-18;
  a21=(a21*a13);
  a21=(a2+a21);
  a22=6.5404420181974428e-19;
  a22=(a22*a16);
  a21=(a21+a22);
  a22=4.8165634579387561e-17;
  a22=(a22*a3);
  a21=(a21+a22);
  a22=3.6363424329129726e-18;
  a22=(a22*a20);
  a21=(a21+a22);
  a23=-2.0794186711538460e-16;
  a23=(a23*a6);
  a21=(a21+a23);
  a23=-3.0158714683697285e-01;
  a23=(a23*a5);
  a24=-7.0108273589749789e-02;
  a24=(a24*a12);
  a23=(a23+a24);
  a24=7.5551087980496057e-01;
  a24=(a24*a10);
  a23=(a23+a24);
  a21=(a21-a23);
  a23=casadi_sq(a21);
  a24=7.0409618142939039e-23;
  a24=(a24*a7);
  a25=3.3322521531167287e-01;
  a25=(a25*a13);
  a24=(a24+a25);
  a25=-2.9724518689063353e-18;
  a25=(a25*a16);
  a24=(a24+a25);
  a25=-8.2833647058313867e-18;
  a25=(a25*a3);
  a24=(a24+a25);
  a25=-1.4308714814178928e-20;
  a25=(a25*a20);
  a24=(a24+a25);
  a25=1.0811802166050903e+00;
  a25=(a25*a6);
  a24=(a24+a25);
  a25=5.0675405294052400e-01;
  a25=(a25*a5);
  a26=-2.0773633988835527e-01;
  a26=(a26*a12);
  a25=(a25+a26);
  a26=1.8301056479646341e-01;
  a26=(a26*a10);
  a25=(a25+a26);
  a24=(a24-a25);
  a25=casadi_sq(a24);
  a23=(a23+a25);
  a25=2.4334847501622316e-02;
  a25=(a25*a7);
  a26=3.1321304933608704e-17;
  a26=(a26*a13);
  a25=(a25+a26);
  a26=3.3311702357776335e-01;
  a26=(a26*a16);
  a25=(a25+a26);
  a26=1.6406149188233443e-15;
  a26=(a26*a3);
  a25=(a25+a26);
  a26=-2.1630975556997614e+00;
  a26=(a26*a20);
  a25=(a25+a26);
  a26=-4.9355101071686617e-17;
  a26=(a26*a6);
  a25=(a25+a26);
  a26=-2.7755575615628914e-17;
  a27=(a26*a10);
  a25=(a25-a27);
  a27=casadi_sq(a25);
  a23=(a23+a27);
  a23=sqrt(a23);
  a23=(a23+a4);
  a21=(a21/a23);
  a21=(a1*a21);
  a14=(a14+a21);
  a21=(a19-a14);
  a21=casadi_sq(a21);
  a27=-2.6700000000000002e-01;
  a17=(a17/a15);
  a17=(a1*a17);
  a27=(a27+a17);
  a24=(a24/a23);
  a24=(a1*a24);
  a17=(a27-a24);
  a17=casadi_sq(a17);
  a21=(a21+a17);
  a17=1.1250000000000000e-02;
  a8=(a8/a15);
  a8=(a1*a8);
  a8=(a17+a8);
  a25=(a25/a23);
  a25=(a1*a25);
  a25=(a17+a25);
  a23=(a8-a25);
  a23=casadi_sq(a23);
  a21=(a21+a23);
  if (res[0]!=0) res[0][0]=a21;
  a21=9.3664866266560915e-05;
  a21=(a21*a13);
  a2=(a2+a21);
  a21=8.1554738618222347e-18;
  a21=(a21*a16);
  a2=(a2+a21);
  a21=-1.0960879673575236e-17;
  a21=(a21*a3);
  a2=(a2+a21);
  a2=(a2+a22);
  a22=-9.3664866266566860e-01;
  a22=(a22*a6);
  a2=(a2+a22);
  a22=5.8950593048665900e-01;
  a22=(a22*a5);
  a21=-1.4478951476015611e-01;
  a21=(a21*a12);
  a22=(a22+a21);
  a21=-2.1931764195228357e-01;
  a21=(a21*a10);
  a22=(a22+a21);
  a2=(a2-a22);
  a22=casadi_sq(a2);
  a21=-2.3726552830630757e-22;
  a21=(a21*a7);
  a7=3.3338739234416370e-01;
  a7=(a7*a13);
  a21=(a21+a7);
  a7=1.0016534411677417e-17;
  a7=(a7*a16);
  a21=(a21+a7);
  a7=2.1879663198888675e-17;
  a7=(a7*a3);
  a21=(a21+a7);
  a7=7.6371381609078201e-21;
  a7=(a7*a20);
  a21=(a21+a7);
  a7=-5.4059010830254473e-01;
  a7=(a7*a6);
  a21=(a21+a7);
  a7=-3.7239084928283935e-02;
  a7=(a7*a5);
  a20=7.6083399347946123e-01;
  a20=(a20*a12);
  a7=(a7+a20);
  a20=5.5737024472460296e-02;
  a20=(a20*a10);
  a7=(a7+a20);
  a21=(a21-a7);
  a7=casadi_sq(a21);
  a22=(a22+a7);
  a7=2.1067415730337099e-02;
  a7=(a7*a13);
  a18=(a18+a7);
  a7=3.3344148821111841e-01;
  a7=(a7*a16);
  a18=(a18+a7);
  a7=1.8726591760299631e+00;
  a7=(a7*a3);
  a18=(a18+a7);
  a18=(a18+a9);
  a9=-4.5172085286893086e-18;
  a9=(a9*a6);
  a18=(a18+a9);
  a11=(a11*a5);
  a26=(a26*a12);
  a11=(a11+a26);
  a26=1.1102230246251565e-16;
  a26=(a26*a10);
  a11=(a11+a26);
  a18=(a18-a11);
  a11=casadi_sq(a18);
  a22=(a22+a11);
  a22=sqrt(a22);
  a22=(a22+a4);
  a2=(a2/a22);
  a2=(a1*a2);
  a0=(a0+a2);
  a19=(a19-a0);
  a19=casadi_sq(a19);
  a2=2.6700000000000002e-01;
  a21=(a21/a22);
  a21=(a1*a21);
  a2=(a2+a21);
  a27=(a27-a2);
  a27=casadi_sq(a27);
  a19=(a19+a27);
  a18=(a18/a22);
  a1=(a1*a18);
  a17=(a17+a1);
  a8=(a8-a17);
  a8=casadi_sq(a8);
  a19=(a19+a8);
  if (res[0]!=0) res[0][1]=a19;
  a14=(a14-a0);
  a14=casadi_sq(a14);
  a24=(a24-a2);
  a24=casadi_sq(a24);
  a14=(a14+a24);
  a25=(a25-a17);
  a25=casadi_sq(a25);
  a14=(a14+a25);
  if (res[0]!=0) res[0][2]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void payload_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void payload_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void payload_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int payload_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int payload_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real payload_model_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* payload_model_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* payload_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int payload_model_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
