N : 10
Tf : 1
pl_max_vel : [30,30,30] #max linear velocity
pl_min_vel : [-30,-30,-30] 
pl_max_omega : [30,30,30 ]   #rad/s for RPY
pl_min_omega : [-30,-30,-30]

dist_r : 0.0
dist_OL  : 0.0
dist_Or : 0.0





